### ISSUE TITLE
npm: Could not find a declaration file for module 'genish.js'

### ISSUE THREAD

**Issue by michaelpalumbo** [charlieroberts/genish.js#24]
I've installed genish.js using node package manager. When importing genish into my script, I receive:

```shell
Could not find a declaration file for module 'genish.js'. 
'D:/github/mischmasch/node_modules/genish.js/js/index.js' implicitly has an 'any' type. 
Try `npm i --save-dev @types/genish.js` if it exists or add a new declaration (.d.ts) file 
containing `declare module 'genish.js';
```

**Comment by michaelpalumbo** [comment]
nevermind. I downloaded /dist/gen.lib.js

**Comment by charlieroberts** [comment]
yeah, that looks like a typescript error… whicj i know nothing about :)

**Comment by michaelpalumbo** [comment]
I see. I also don't know anything about typescript. fortunately once i installed it the way i was supposed to it worked fine ;)
